git mv components/about-section.tsx components/AboutSection.tsx
git mv components/background-particles.tsx components/BackgroundParticles.tsx
git mv components/contact-section.tsx components/ContactSection.tsx
git mv components/cursor-glow.tsx components/CursorGlow.tsx
git mv components/experience-section.tsx components/ExperienceSection.tsx
git mv components/footer.tsx components/Footer.tsx
git mv components/header.tsx components/Header.tsx
git mv components/hero-section.tsx components/HeroSection.tsx
git mv components/loading-screen.tsx components/LoadingScreen.tsx
git mv components/project-detail-client.tsx components/ProjectDetailClient.tsx
git mv components/projects-section.tsx components/ProjectsSection.tsx
git mv components/scroll-to-top.tsx components/ScrollToTop.tsx
git mv components/skills-section.tsx components/SkillsSection.tsx
git mv components/theme-provider.tsx components/ThemeProvider.tsx
git mv components/toast-provider.tsx components/ToastProvider.tsx
git mv components/view-tracker.tsx components/ViewTracker.tsx
git mv components/admin/sidebar.tsx components/admin/Sidebar.tsx
